// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:691930476460:web:902626b04bad681fd89409',
    messagingSenderId: '691930476460',
    projectId: 'project-pet-care',
    authDomain: 'project-pet-care.firebaseapp.com',
    storageBucket: 'project-pet-care.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:691930476460:android:56cd6024505ef4cbd89409',
    messagingSenderId: '691930476460',
    projectId: 'project-pet-care',
    storageBucket: 'project-pet-care.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:691930476460:ios:7a234457170ddf48d89409',
    messagingSenderId: '691930476460',
    projectId: 'project-pet-care',
    storageBucket: 'project-pet-care.appspot.com',
    iosBundleId: 'com.example.petCareConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:691930476460:ios:31e63a721ef42c1cd89409',
    messagingSenderId: '691930476460',
    projectId: 'project-pet-care',
    storageBucket: 'project-pet-care.appspot.com',
    iosBundleId: 'com.example.petCareConnect.RunnerTests',
  );
}
